In [2]:
import numpy as np
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_)

In [11]:
# Question 1

print('Datatype of list_ is :' , type(list_))
print("Datatype of array_list is:" , type(array_list))


"""Yes ,there is difference in the datatype of list_ and array_list variables.
The list_ variable datatype is python list of strings whereas array_list is a numpy array of strings although they both contain 
same string values but they have different datatypes because they are different types of objects."""

Datatype of list_ is : <class 'list'>
Datatype of array_list is: <class 'numpy.ndarray'>


'Yes ,there is difference in the datatype of list_ and array_list variables.\nThe list_ variable datatype is python list of strings whereas array_list is a numpy array of strings although they both contain \nsame string values but they have different datatypes because they are different types of objects.'

In [12]:
# Question 2

# Datatype of each and every element in list_

for i in list_:
    print(f'The given element : {i} , Datatype = {type(i)}' )

The given element : 1 , Datatype = <class 'str'>
The given element : 2 , Datatype = <class 'str'>
The given element : 3 , Datatype = <class 'str'>
The given element : 4 , Datatype = <class 'str'>
The given element : 5 , Datatype = <class 'str'>


In [13]:
# Datatype of each element in array_list

for j in array_list:
    print(f'The given element : {j} , Datatype = {type(j)}' )

The given element : 1 , Datatype = <class 'numpy.str_'>
The given element : 2 , Datatype = <class 'numpy.str_'>
The given element : 3 , Datatype = <class 'numpy.str_'>
The given element : 4 , Datatype = <class 'numpy.str_'>
The given element : 5 , Datatype = <class 'numpy.str_'>


In [20]:
# Question 3

array_list = np.array(object = list_, dtype = int)

array_list

"""Yes there is difference in the datatype of the elements present in both variables .
list_variable datatype is list of strings and array_list datatype is now change into numpy integer."""

# Code to show the datatype of both the variables 

print('Datatype of every element in list_','\n')

for i in list_:
    print(f'The given element : {i} , Datatype = {type(i)}' )
    
print('\n')    
print('Datatype of every element in array_list','\n')

for j in array_list:
    print(f'The given element : {j} , Datatype = {type(j)}' )

Datatype of every element in list_ 

The given element : 1 , Datatype = <class 'str'>
The given element : 2 , Datatype = <class 'str'>
The given element : 3 , Datatype = <class 'str'>
The given element : 4 , Datatype = <class 'str'>
The given element : 5 , Datatype = <class 'str'>


Datatype of every element in array_list 

The given element : 1 , Datatype = <class 'numpy.int64'>
The given element : 2 , Datatype = <class 'numpy.int64'>
The given element : 3 , Datatype = <class 'numpy.int64'>
The given element : 4 , Datatype = <class 'numpy.int64'>
The given element : 5 , Datatype = <class 'numpy.int64'>


In [21]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [31]:
# Question 4

print('Showing num_array shape:','\n')

print(num_array.shape)


print('Showing num_array size:','\n')


print(num_array.size)

Showing num_array shape: 

(2, 3)
Showing num_array size: 

6


In [51]:
# Question 5

# Creating matrix of 3*3 containig zero only through zeroes func

arr = np.zeros((3 ,3))

print(arr , '\n')
# Veryfying matrix size and shape

print('Size of the matrix:',arr.size , '\n')

print('Shape of the matrix:',arr.shape , '\n')


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

Size of the matrix: 9 

Shape of the matrix: (3, 3) 



In [56]:
# Question 6

# Creating identity matrix of 5*5 

eye_arr = np.eye(5,5)

print('Identity matrix(5,5):','\n' ,eye_arr)

Identity matrix(5,5): 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
